// Generated by packages/design-tokens/generate.py. Do not edit directly.
import 'package:flutter/material.dart';

class RailOSTokens {
  RailOSTokens._();

  // Dimensions
  static const double minTouchTargetDp = 48.0;
  static const double evidenceStripHeightDp = 64.0;
  static const double photoPreviewMaxHeightDp = 400.0;
  static const double videoOverlayFontSizeSp = 14.0;
  static const double borderRadiusSm = 4.0;
  static const double borderRadiusMd = 8.0;
  static const double borderRadiusLg = 12.0;
  static const double spacingXs = 4.0;
  static const double spacingSm = 8.0;
  static const double spacingMd = 16.0;
  static const double spacingLg = 24.0;
  static const double spacingXl = 32.0;

  // Geo & Constraints
  static const double defaultTaskRadiusMeters = 100.0;
  static const double targetGpsAccuracyMeters = 50.0;
  static const int maxFixAgeSeconds = 30;
  static const int maxClockDriftSeconds = 300;
  static const int videoSampleIntervalSeconds = 5;

  // Media Constraints
  static const int maxVideoDurationSeconds = 90;
  static const int videoResolutionWidth = 1280;
  static const int videoResolutionHeight = 720;
  static const int photoCompressionQuality = 85;
  static const int multipartChunkSizeBytes = 8388608;

  // Colors
  static const Color primary_navy = Color(0xFF0B1528);
  static const Color primary_steel = Color(0xFF1E293B);
  static const Color primary_railBlue = Color(0xFF1D4ED8);
  static const Color primary_signalAmber = Color(0xFFD97706);
  static const Color primary_safetyRed = Color(0xFFDC2626);
  static const Color primary_trackGreen = Color(0xFF059669);
  static const Color bg_darkRoot = Color(0xFF070D18);
  static const Color bg_darkSurface = Color(0xFF0F172A);
  static const Color bg_darkElevated = Color(0xFF1E293B);
  static const Color bg_darkBorder = Color(0xFF334155);
  static const Color bg_lightRoot = Color(0xFFF8FAFC);
  static const Color bg_lightSurface = Color(0xFFFFFFFF);
  static const Color bg_lightElevated = Color(0xFFF1F5F9);
  static const Color bg_lightBorder = Color(0xFFE2E8F0);
  static const Color status_verified_bg = Color(0xFF064E3B);
  static const Color status_verified_border = Color(0xFF059669);
  static const Color status_verified_fg = Color(0xFF34D399);
  static const Color status_verified_text = Color(0xFFECFDF5);
  static const Color status_verifying_bg = Color(0xFF1E3A8A);
  static const Color status_verifying_border = Color(0xFF2563EB);
  static const Color status_verifying_fg = Color(0xFF60A5FA);
  static const Color status_verifying_text = Color(0xFFEFF6FF);
  static const Color status_flagged_bg = Color(0xFF581C87);
  static const Color status_flagged_border = Color(0xFF7C3AED);
  static const Color status_flagged_fg = Color(0xFFA78BFA);
  static const Color status_flagged_text = Color(0xFFF5F3FF);
  static const Color status_caution_bg = Color(0xFF78350F);
  static const Color status_caution_border = Color(0xFFD97706);
  static const Color status_caution_fg = Color(0xFFFBBF24);
  static const Color status_caution_text = Color(0xFFFFFBEB);
  static const Color status_rejected_bg = Color(0xFF7F1D1D);
  static const Color status_rejected_border = Color(0xFFDC2626);
  static const Color status_rejected_fg = Color(0xFFF87171);
  static const Color status_rejected_text = Color(0xFFFEF2F2);
  static const Color status_draft_bg = Color(0xFF1E293B);
  static const Color status_draft_border = Color(0xFF475569);
  static const Color status_draft_fg = Color(0xFF94A3B8);
  static const Color status_draft_text = Color(0xFFF8FAFC);
}
