// Generated by packages/design-tokens/generate.py. Do not edit directly.
// ignore_for_file: constant_identifier_names
import 'package:flutter/material.dart';

class RailOSTokens {
  RailOSTokens._();

  // Dimensions
  static const double minTouchTargetDp = 48.0;
  static const double evidenceStripHeightDp = 64.0;
  static const double photoPreviewMaxHeightDp = 400.0;
  static const double videoOverlayFontSizeSp = 14.0;
  static const double borderRadiusSm = 4.0;
  static const double borderRadiusMd = 8.0;
  static const double borderRadiusLg = 12.0;
  static const double spacingXs = 4.0;
  static const double spacingSm = 8.0;
  static const double spacingMd = 16.0;
  static const double spacingLg = 24.0;
  static const double spacingXl = 32.0;

  // Geo & Constraints
  static const double defaultTaskRadiusMeters = 100.0;
  static const double targetGpsAccuracyMeters = 50.0;
  static const int maxFixAgeSeconds = 30;
  static const int maxClockDriftSeconds = 300;
  static const int videoSampleIntervalSeconds = 5;

  // Media Constraints
  static const int maxVideoDurationSeconds = 90;
  static const int videoResolutionWidth = 1280;
  static const int videoResolutionHeight = 720;
  static const int photoCompressionQuality = 85;
  static const int multipartChunkSizeBytes = 8388608;

  // Core RailOS Cockpit Design Tokens
  static const Color bg_canvas = Color(0xFF121313);
  static const Color bg_surface = Color(0xFF181917);
  static const Color bg_panel = Color(0xFF1C1C1A);
  static const Color bg_elevated = Color(0xFF21201D);
  static const Color bg_overlay = Color(0xFF0A0703);
  static const Color bg_accent = Color(0xFFE8A317);
  static const Color accent = Color(0xFFE8A317);

  // Borders
  static const Color border_default = Color(0xFF3A372F);
  static const Color border_subtle = Color(0xFF292722);
  static const Color border_strong = Color(0xFF554D3F);

  // Typography Inks
  static const Color text_primary = Color(0xFFF3EFE5);
  static const Color text_secondary = Color(0xFFC1BBAD);
  static const Color text_muted = Color(0xFF918B80);
  static const Color text_darkPrimary = Color(0xFFF3EFE5);
  static const Color text_darkSecondary = Color(0xFFC1BBAD);
  static const Color text_darkMuted = Color(0xFF918B80);
  static const Color text_lightPrimary = Color(0xFF121313);
  static const Color text_lightSecondary = Color(0xFF3A372F);
  static const Color text_lightMuted = Color(0xFF554D3F);

  // Semantic Status Tokens
  static const Color status_ok_bg = Color(0xFF1A3A2A);
  static const Color status_ok_border = Color(0xFF2D5A42);
  static const Color status_ok_fg = Color(0xFF8FB38B);
  static const Color status_ok_text = Color(0xFFC8E6C1);
  static const Color status_verified_bg = Color(0xFF1A3A2A);
  static const Color status_verified_border = Color(0xFF2D5A42);
  static const Color status_verified_fg = Color(0xFF8FB38B);
  static const Color status_verified_text = Color(0xFFC8E6C1);
  static const Color status_info_bg = Color(0xFF1A3A4A);
  static const Color status_info_border = Color(0xFF2D5A7A);
  static const Color status_info_fg = Color(0xFF6B9AC4);
  static const Color status_info_text = Color(0xFFB3D9F2);
  static const Color status_verifying_bg = Color(0xFF1A3A4A);
  static const Color status_verifying_border = Color(0xFF2D5A7A);
  static const Color status_verifying_fg = Color(0xFF6B9AC4);
  static const Color status_verifying_text = Color(0xFFB3D9F2);
  static const Color status_caution_bg = Color(0xFF3A2F1A);
  static const Color status_caution_border = Color(0xFF5A4A2D);
  static const Color status_caution_fg = Color(0xFFD39A59);
  static const Color status_caution_text = Color(0xFFF0C884);
  static const Color status_warning_bg = Color(0xFF3A2A1A);
  static const Color status_warning_border = Color(0xFF5A4A2D);
  static const Color status_warning_fg = Color(0xFFE8A317);
  static const Color status_warning_text = Color(0xFFFFC966);
  static const Color status_critical_bg = Color(0xFF3A1A1A);
  static const Color status_critical_border = Color(0xFF5A2D2D);
  static const Color status_critical_fg = Color(0xFFD97864);
  static const Color status_critical_text = Color(0xFFF5A898);
  static const Color status_rejected_bg = Color(0xFF3A1A1A);
  static const Color status_rejected_border = Color(0xFF5A2D2D);
  static const Color status_rejected_fg = Color(0xFFD97864);
  static const Color status_rejected_text = Color(0xFFF5A898);
  static const Color status_blocked_bg = Color(0xFF2A1F3A);
  static const Color status_blocked_border = Color(0xFF3D2D5A);
  static const Color status_blocked_fg = Color(0xFFA27DD4);
  static const Color status_blocked_text = Color(0xFFD9C9F0);
  static const Color status_flagged_bg = Color(0xFF2A1F3A);
  static const Color status_flagged_border = Color(0xFF3D2D5A);
  static const Color status_flagged_fg = Color(0xFFA27DD4);
  static const Color status_flagged_text = Color(0xFFD9C9F0);
  static const Color status_unknown_bg = Color(0xFF262421);
  static const Color status_unknown_border = Color(0xFF3A372F);
  static const Color status_unknown_fg = Color(0xFF918B80);
  static const Color status_unknown_text = Color(0xFFC1BBAD);
  static const Color status_draft_bg = Color(0xFF262421);
  static const Color status_draft_border = Color(0xFF3A372F);
  static const Color status_draft_fg = Color(0xFF918B80);
  static const Color status_draft_text = Color(0xFFC1BBAD);

  // Department Tokens
  static const Color dept_engg_bg = Color(0xFF3A2A1A);
  static const Color dept_engg_border = Color(0xFF5A4A2D);
  static const Color dept_engg_fg = Color(0xFFD4A059);
  static const Color dept_engg_text = Color(0xFFE8B77D);
  static const Color dept_snt_bg = Color(0xFF3A2F1A);
  static const Color dept_snt_border = Color(0xFF5A4A2D);
  static const Color dept_snt_fg = Color(0xFFE8A317);
  static const Color dept_snt_text = Color(0xFFFFC966);
  static const Color dept_trd_bg = Color(0xFF1A3A2A);
  static const Color dept_trd_border = Color(0xFF2D5A42);
  static const Color dept_trd_fg = Color(0xFF7AAC8F);
  static const Color dept_trd_text = Color(0xFFA8D4B8);

  // Evidence Strip Tokens
  static const Color evidenceStrip_overlayBg = Color(0xE00A0703);
  static const Color evidenceStrip_overlayText = Color(0xFFF3EFE5);
  static const Color evidenceStrip_overlayAccent = Color(0xFFE8A317);
  static const Color evidenceStrip_overlayWarning = Color(0xFFD39A59);
  static const Color evidenceStrip_overlayAlert = Color(0xFFD97864);

  // Backward-Compatible Primary & Background Aliases
  static const Color primary_accent = Color(0xFFE8A317);
  static const Color primary_signalAmber = Color(0xFFE8A317);
  static const Color primary_safetyRed = Color(0xFFD97864);
  static const Color primary_trackGreen = Color(0xFF8FB38B);
  static const Color primary_railBlue = Color(0xFF6B9AC4);
  static const Color primary_navy = Color(0xFF121313);
  static const Color primary_steel = Color(0xFF181917);
  static const Color bg_darkRoot = Color(0xFF121313);
  static const Color bg_darkSurface = Color(0xFF181917);
  static const Color bg_darkPanel = Color(0xFF1C1C1A);
  static const Color bg_darkElevated = Color(0xFF21201D);
  static const Color bg_darkBorder = Color(0xFF3A372F);
  static const Color bg_lightRoot = Color(0xFFF3EFE5);
  static const Color bg_lightSurface = Color(0xFFFFFFFF);
  static const Color bg_lightElevated = Color(0xFFEFEBE0);
  static const Color bg_lightBorder = Color(0xFF3A372F);
}
