#!/usr/bin/env python3
"""Generate platform-specific tokens from canonical tokens.json."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).parent
TOKENS_FILE = ROOT / "tokens.json"
DIST_DIR = ROOT / "dist"


def generate():
    DIST_DIR.mkdir(parents=True, exist_ok=True)
    with open(TOKENS_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    # 1. Generate CSS
    css_lines = [
        "/* Generated by packages/design-tokens/generate.py. Do not edit directly. */",
        ":root {",
    ]
    # Primary colors
    for k, v in data["colors"]["primary"].items():
        css_lines.append(f"  --color-primary-{k}: {v};")

    # Backgrounds & texts
    for k, v in data["colors"]["background"].items():
        css_lines.append(f"  --color-bg-{k}: {v};")
    for k, v in data["colors"]["text"].items():
        css_lines.append(f"  --color-text-{k}: {v};")

    # Status tokens
    for status_key, status_obj in data["colors"]["status"].items():
        for prop_key, val in status_obj.items():
            css_lines.append(f"  --status-{status_key}-{prop_key}: {val};")

    # Evidence strip
    for k, v in data["colors"]["evidenceStrip"].items():
        css_lines.append(f"  --evidence-strip-{k}: {v};")

    # Dimensions
    for k, v in data["dimensions"].items():
        css_lines.append(f"  --dimension-{k}: {v}px;")

    css_lines.append("}\n")
    css_content = "\n".join(css_lines)
    (DIST_DIR / "railos_tokens.css").write_text(css_content, encoding="utf-8")

    # 2. Generate Dart
    dart_lines = [
        "// Generated by packages/design-tokens/generate.py. Do not edit directly.",
        "import 'package:flutter/material.dart';",
        "",
        "class RailOSTokens {",
        "  RailOSTokens._();",
        "",
        "  // Dimensions",
    ]
    for k, v in data["dimensions"].items():
        dart_lines.append(f"  static const double {k} = {float(v)};")

    dart_lines.append("\n  // Geo & Constraints")
    for k, v in data["geo"].items():
        val_str = f"{float(v)}" if isinstance(v, float) else str(v)
        dart_lines.append(f"  static const {type(v).__name__} {k} = {val_str};")

    dart_lines.append("\n  // Media Constraints")
    for k, v in data["media"].items():
        dart_lines.append(f"  static const int {k} = {v};")

    dart_lines.append("\n  // Colors")

    def _hex_to_flutter_color(hex_str: str) -> str:
        if hex_str.startswith("#"):
            clean = hex_str.lstrip("#")
            return f"Color(0xFF{clean.upper()})"
        if hex_str.startswith("rgba"):
            return "Color(0xD1000000)"
        return "Color(0xFF000000)"

    for k, v in data["colors"]["primary"].items():
        dart_lines.append(f"  static const Color primary_{k} = {_hex_to_flutter_color(v)};")

    for k, v in data["colors"]["background"].items():
        dart_lines.append(f"  static const Color bg_{k} = {_hex_to_flutter_color(v)};")

    for status_key, status_obj in data["colors"]["status"].items():
        for prop_key, val in status_obj.items():
            dart_lines.append(
                f"  static const Color status_{status_key}_{prop_key} = {_hex_to_flutter_color(val)};"
            )

    dart_lines.append("}\n")
    dart_content = "\n".join(dart_lines)
    (DIST_DIR / "railos_tokens.dart").write_text(dart_content, encoding="utf-8")

    # 3. Generate TypeScript
    ts_lines = [
        "// Generated by packages/design-tokens/generate.py. Do not edit directly.",
        f"export const railosTokens = {json.dumps(data, indent=2)} as const;",
        "export type RailOSTokens = typeof railosTokens;",
        "",
    ]
    (DIST_DIR / "railos_tokens.ts").write_text("\n".join(ts_lines), encoding="utf-8")
    print("Tokens generated successfully in packages/design-tokens/dist/")


if __name__ == "__main__":
    generate()
