#!/usr/bin/env python3
"""Generate platform-specific tokens from canonical tokens.json."""

from __future__ import annotations

import json
from pathlib import Path
import shutil

ROOT = Path(__file__).parent
TOKENS_FILE = ROOT / "tokens.json"
DIST_DIR = ROOT / "dist"
FLUTTER_THEME_DIR = ROOT.parent.parent / "apps" / "field-app" / "lib" / "theme"
NEXTJS_APP_DIR = ROOT.parent.parent / "apps" / "control-center" / "src" / "app"


def _hex_to_flutter_color(hex_str: str) -> str:
    if hex_str.startswith("#"):
        clean = hex_str.lstrip("#")
        return f"Color(0xFF{clean.upper()})"
    if hex_str.startswith("rgba"):
        # approximate rgba(10, 7, 3, 0.88)
        return "Color(0xE00A0703)"
    return "Color(0xFF000000)"


def generate():
    DIST_DIR.mkdir(parents=True, exist_ok=True)
    with open(TOKENS_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    # 1. Generate CSS
    css_lines = [
        "/* Generated by packages/design-tokens/generate.py. Do not edit directly. */",
        ":root {",
    ]

    # Core surface tokens
    for key in ["canvas", "surface", "panel", "elevated", "overlay", "accent"]:
        if key in data["colors"]:
            css_lines.append(f"  --bg-{key}: {data['colors'][key]};")

    # Border tokens
    for k, v in data["colors"]["border"].items():
        css_lines.append(f"  --border-{k}: {v};")

    # Text tokens
    for k, v in data["colors"]["text"].items():
        css_lines.append(f"  --text-{k}: {v};")

    # Primary colors
    for k, v in data["colors"]["primary"].items():
        css_lines.append(f"  --color-primary-{k}: {v};")

    # Backgrounds & texts
    for k, v in data["colors"]["background"].items():
        css_lines.append(f"  --color-bg-{k}: {v};")

    # Status tokens
    for status_key, status_obj in data["colors"]["status"].items():
        for prop_key, val in status_obj.items():
            css_lines.append(f"  --status-{status_key}-{prop_key}: {val};")

    # Department tokens
    if "departments" in data["colors"]:
        for dept_key, dept_obj in data["colors"]["departments"].items():
            for prop_key, val in dept_obj.items():
                css_lines.append(f"  --dept-{dept_key}-{prop_key}: {val};")

    # Evidence strip
    for k, v in data["colors"]["evidenceStrip"].items():
        css_lines.append(f"  --evidence-strip-{k}: {v};")

    # Dimensions
    for k, v in data["dimensions"].items():
        css_lines.append(f"  --dimension-{k}: {v}px;")

    css_lines.append("}\n")
    css_content = "\n".join(css_lines)
    (DIST_DIR / "railos_tokens.css").write_text(css_content, encoding="utf-8")

    # 2. Generate Dart
    dart_lines = [
        "// Generated by packages/design-tokens/generate.py. Do not edit directly.",
        "// ignore_for_file: constant_identifier_names",
        "import 'package:flutter/material.dart';",
        "",
        "class RailOSTokens {",
        "  RailOSTokens._();",
        "",
        "  // Dimensions",
    ]
    for k, v in data["dimensions"].items():
        dart_lines.append(f"  static const double {k} = {float(v)};")

    dart_lines.append("\n  // Geo & Constraints")
    for k, v in data["geo"].items():
        dart_type = "double" if isinstance(v, float) else "int"
        val_str = f"{float(v)}" if isinstance(v, float) else str(v)
        dart_lines.append(f"  static const {dart_type} {k} = {val_str};")

    dart_lines.append("\n  // Media Constraints")
    for k, v in data["media"].items():
        dart_lines.append(f"  static const int {k} = {v};")

    dart_lines.append("\n  // Core RailOS Cockpit Design Tokens")
    for key in ["canvas", "surface", "panel", "elevated", "overlay", "accent"]:
        if key in data["colors"]:
            dart_lines.append(
                f"  static const Color bg_{key} = {_hex_to_flutter_color(data['colors'][key])};"
            )
    dart_lines.append(f"  static const Color accent = {_hex_to_flutter_color(data['colors']['accent'])};")

    dart_lines.append("\n  // Borders")
    for k, v in data["colors"]["border"].items():
        dart_lines.append(
            f"  static const Color border_{k} = {_hex_to_flutter_color(v)};"
        )

    dart_lines.append("\n  // Typography Inks")
    for k, v in data["colors"]["text"].items():
        dart_lines.append(
            f"  static const Color text_{k} = {_hex_to_flutter_color(v)};"
        )

    dart_lines.append("\n  // Semantic Status Tokens")
    for status_key, status_obj in data["colors"]["status"].items():
        for prop_key, val in status_obj.items():
            dart_lines.append(
                f"  static const Color status_{status_key}_{prop_key} = {_hex_to_flutter_color(val)};"
            )

    dart_lines.append("\n  // Department Tokens")
    if "departments" in data["colors"]:
        for dept_key, dept_obj in data["colors"]["departments"].items():
            for prop_key, val in dept_obj.items():
                dart_lines.append(
                    f"  static const Color dept_{dept_key}_{prop_key} = {_hex_to_flutter_color(val)};"
                )

    dart_lines.append("\n  // Evidence Strip Tokens")
    for k, v in data["colors"]["evidenceStrip"].items():
        dart_lines.append(
            f"  static const Color evidenceStrip_{k} = {_hex_to_flutter_color(v)};"
        )

    dart_lines.append("\n  // Backward-Compatible Primary & Background Aliases")
    for k, v in data["colors"]["primary"].items():
        dart_lines.append(f"  static const Color primary_{k} = {_hex_to_flutter_color(v)};")

    for k, v in data["colors"]["background"].items():
        dart_lines.append(f"  static const Color bg_{k} = {_hex_to_flutter_color(v)};")

    dart_lines.append("}\n")
    dart_content = "\n".join(dart_lines)
    (DIST_DIR / "railos_tokens.dart").write_text(dart_content, encoding="utf-8")

    # 3. Generate TypeScript
    ts_lines = [
        "// Generated by packages/design-tokens/generate.py. Do not edit directly.",
        f"export const railosTokens = {json.dumps(data, indent=2)} as const;",
        "export type RailOSTokens = typeof railosTokens;",
        "",
    ]
    (DIST_DIR / "railos_tokens.ts").write_text("\n".join(ts_lines), encoding="utf-8")

    # Copy to app destinations if they exist
    if FLUTTER_THEME_DIR.exists():
        (FLUTTER_THEME_DIR / "railos_tokens.dart").write_text(dart_content, encoding="utf-8")
        print(f"Copied railos_tokens.dart to {FLUTTER_THEME_DIR}")

    if NEXTJS_APP_DIR.exists():
        (NEXTJS_APP_DIR / "railos_tokens.css").write_text(css_content, encoding="utf-8")
        print(f"Copied railos_tokens.css to {NEXTJS_APP_DIR}")

    print("Tokens generated successfully in packages/design-tokens/dist/")


if __name__ == "__main__":
    generate()
