-- PostgreSQL schema; API defaults to the thread-safe in-memory store.
CREATE TABLE IF NOT EXISTS corridors (id text PRIMARY KEY, name text NOT NULL, from_station text NOT NULL, to_station text NOT NULL, synthetic boolean NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS assets (id text PRIMARY KEY, corridor_id text NOT NULL REFERENCES corridors(id), name text NOT NULL, asset_type text NOT NULL, criticality integer NOT NULL CHECK (criticality BETWEEN 1 AND 10), km numeric NOT NULL, synthetic boolean NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS maintenance_tasks (id text PRIMARY KEY, corridor_id text NOT NULL REFERENCES corridors(id), asset_id text REFERENCES assets(id), title text NOT NULL, department text NOT NULL, duration_minutes integer NOT NULL CHECK (duration_minutes > 0), priority integer NOT NULL CHECK (priority BETWEEN 1 AND 100), critical boolean NOT NULL DEFAULT false, overdue boolean NOT NULL DEFAULT false, status text NOT NULL DEFAULT 'PENDING', synthetic boolean NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS defects (id text PRIMARY KEY, asset_id text REFERENCES assets(id), severity text NOT NULL, description text NOT NULL, critical boolean NOT NULL DEFAULT false, status text NOT NULL DEFAULT 'OPEN', synthetic boolean NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS train_movements (id text PRIMARY KEY, corridor_id text NOT NULL REFERENCES corridors(id), train_number text NOT NULL, train_class text NOT NULL, starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, synthetic boolean NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS block_windows (id text PRIMARY KEY, corridor_id text NOT NULL REFERENCES corridors(id), starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, block_type text NOT NULL, synthetic boolean NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS plans (id text NOT NULL, version integer NOT NULL, state text NOT NULL, payload jsonb NOT NULL, created_at timestamptz NOT NULL, PRIMARY KEY (id, version));
CREATE TABLE IF NOT EXISTS domain_events (sequence bigserial PRIMARY KEY, id text UNIQUE NOT NULL, event_type text NOT NULL, entity_id text NOT NULL, payload jsonb NOT NULL, occurred_at timestamptz NOT NULL, synthetic boolean NOT NULL DEFAULT true);
CREATE INDEX IF NOT EXISTS idx_tasks_corridor_status ON maintenance_tasks(corridor_id, status);
CREATE INDEX IF NOT EXISTS idx_events_entity_sequence ON domain_events(entity_id, sequence);
