CREATE TABLE IF NOT EXISTS users (user_id text PRIMARY KEY, display_name text NOT NULL, role text NOT NULL);
CREATE TABLE IF NOT EXISTS roles (role text PRIMARY KEY);
CREATE TABLE IF NOT EXISTS resources (resource_id text PRIMARY KEY, resource_type text NOT NULL, department text NOT NULL, home_section_id text NOT NULL);
CREATE TABLE IF NOT EXISTS dependencies (predecessor_task_id text NOT NULL, successor_task_id text NOT NULL, lag_minutes integer NOT NULL DEFAULT 0, PRIMARY KEY (predecessor_task_id, successor_task_id));
CREATE TABLE IF NOT EXISTS goods_forecasts (rake_id text PRIMARY KEY, section_id text NOT NULL, track text NOT NULL, window_start integer NOT NULL, window_end integer NOT NULL, probability numeric NOT NULL CHECK (probability BETWEEN 0 AND 1));
CREATE TABLE IF NOT EXISTS block_requests (request_id text PRIMARY KEY, section_id text NOT NULL, requested_by text NOT NULL, status text NOT NULL);
CREATE TABLE IF NOT EXISTS optimization_runs (run_id text PRIMARY KEY, status text NOT NULL, solver_status text NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS plan_versions (plan_id text NOT NULL, version integer NOT NULL, parent_plan_id text, status text NOT NULL, immutable boolean NOT NULL DEFAULT false, payload jsonb NOT NULL, PRIMARY KEY(plan_id,version));
CREATE TABLE IF NOT EXISTS scheduled_blocks (block_id text PRIMARY KEY, plan_id text NOT NULL, plan_version integer NOT NULL, section_id text NOT NULL, starts_at integer NOT NULL, ends_at integer NOT NULL);
CREATE TABLE IF NOT EXISTS plan_assignments (plan_id text NOT NULL, plan_version integer NOT NULL, task_id text NOT NULL, block_id text NOT NULL, start_minute integer NOT NULL, end_minute integer NOT NULL, locked boolean NOT NULL DEFAULT false, PRIMARY KEY(plan_id,plan_version,task_id));
CREATE TABLE IF NOT EXISTS work_updates (update_id text PRIMARY KEY, task_id text NOT NULL, status text NOT NULL, note text NOT NULL, actor text NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS emergencies (emergency_id text PRIMARY KEY, corridor_id text NOT NULL, severity text NOT NULL, payload jsonb NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS notifications (notification_id text PRIMARY KEY, event_id text NOT NULL, acknowledged boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS audit_logs (audit_id bigserial PRIMARY KEY, event_id text NOT NULL, actor text NOT NULL, action text NOT NULL, before_json jsonb, after_json jsonb, reason text, plan_version integer, occurred_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS analytics_snapshots (snapshot_id text PRIMARY KEY, label text NOT NULL, payload jsonb NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS adapter_checkpoints (source text PRIMARY KEY, cursor text NOT NULL, source_version text NOT NULL, updated_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS idempotency_keys (actor text NOT NULL, route text NOT NULL, key text NOT NULL, fingerprint text NOT NULL, response jsonb NOT NULL, created_at timestamptz NOT NULL, PRIMARY KEY(actor,route,key));
CREATE INDEX IF NOT EXISTS idx_plan_assignments_task ON plan_assignments(task_id);
CREATE INDEX IF NOT EXISTS idx_audit_plan_version ON audit_logs(plan_version);
